config/routes.rb
Rails.application.routes.draw do
  resources :increase_points
  resources :match_predections
  # resources :users
  get '/users', to:'users#index'
  root 'match_predections#index'
  get '/winners', to: 'increase_points#view_winners'
  # get '/increase_points/new', to:'increase_points#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all.order(point: :desc)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: "User was successfully updated." }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1 or /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: "User was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :point, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :point %>
    <%= form.number_field :point %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Page not found</h1>
<%if false%>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1 style="color:red;text-align:center;font-family:'Georgia';font-style: italic"><b>Scoreboard</b></h1>
<br><br><br>
<center>
<b><%= link_to 'Home',root_path, class: 'button' %></b>
<b><%= link_to 'Daily Winners list',winners_path, class: 'button' %></b>
</center>
<br><br><br>
<table id='scoreboard'>
  <thead>
    <tr>
      <th>Rank <span style="font-size: 150%">🏆</span> </th>
      <th>Players</th>
      <th>Point</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, i| %>
      <tr>
        <td>
          <%if i ==0 %>
          <%= i+1 %>
          <% else %>
            <%= i+1 %>
          <%end%>
        </td>
        
        <td>
          <%if i ==0 %>
            <b><%= user.name %></b><span style="font-size: 200%">🥇</span>
            <%elsif i==1%>
            <b><%= user.name %></b><span style="font-size: 200%">🥈</span>
            <%elsif i==2%>
            <b><%= user.name %></b><span style="font-size: 200%">🥉</span>
          <% else %>
            <b><%= user.name %></b>
          <%end%>
        </td>
        
        <td style='color:blue'><b><%= user.point %></b></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Page not found</h1>
<% if false%>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Page not found</h1>
<% if false %>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Point:</strong>
  <%= @user.point %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<% end %>