config/routes.rb
Rails.application.routes.draw do
  resources :increase_points
  resources :match_predections
  # resources :users
  get '/users', to:'users#index'
  root 'match_predections#index'
  get '/winners', to: 'increase_points#view_winners'
  # get '/increase_points/new', to:'increase_points#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/increase_point.rb
class IncreasePoint < ApplicationRecord
end

app/controllers/increase_points_controller.rb
class IncreasePointsController < ApplicationController
  before_action :set_increase_point, only: %i[ show edit update destroy ]
  # GET /increase_points or /increase_points.json
  def index
    @increase_points = IncreasePoint.all
  end

  # GET /increase_points/1 or /increase_points/1.json
  def show
  end

  # GET /increase_points/new
  def new
    @increase_point = IncreasePoint.new
  end

  def increase_user_points
    @match_predections = MatchPredection.all
    @users = User.all.order(point: :desc)
    winner2 = @increase_point.winner2 
    @match1_winners = @match_predections.where(date: @increase_point.date, winners1: @increase_point.winner1 )
    @match1_winners.each do |winner|
      user = @users.find_by_name(winner.name)
      user.point +=1 
      user.save!
    end
    unless winner2.empty?
      @match2_winners = @match_predections.where(date: @increase_point.date, winners2: @increase_point.winner2)
      @match2_winners.each do |winner| 
        user = @users.find_by_name(winner.name)
        user.point +=1 
        user.save!
      end
    end
  end

  # def get_date
  #   today = Time.now.utc.strftime("%d-%b-%y")
  #   match_start_date = "9-Apr-21"
  #   today >= match_start_date ? today : match_start_date
  # end

  def daywise_winners_list
    get_date = MatchPredectionsHelper.get_date
    winners_team = IncreasePoint.all.find_by(date: get_date)
    match_schedule = MatchPredectionsHelper::MATCH_SCHEDULE[get_date]
    winner_team1 = winners_team.winner1
    winner_team2 = winners_team.winner2
    winners2 = nil
    matches = []
    match_schedule.each do |match|
      matches << "#{match['team1']} VS #{match['team2']}"
    end
    match1 = matches[0]
    match2 = matches[1]
    winners1 = MatchPredection.all.where(date: get_date, winners1: winner_team1).select('name').map{|b| b.name}.join(', ')
    unless winner_team2.empty?
      winners2 = MatchPredection.all.where(date: get_date, winners2: winner_team2).select('name').map{|b| b.name}.join(', ')
    end
    winners_list = WinnerTeamsUser.new({date: get_date, winners1: winners1, winners2: winners2,match1: match1, match2: match2, team1: winner_team1,team2: winner_team2})
    winners_list.save!
  end

  def view_winners
  end

  def check_password(increase_point_params)
    increase_point_params['password'] == ENV['PASSWORD']
  end

  # GET /increase_points/1/edit
  def edit
  end

  # POST /increase_points or /increase_points.json
  def create
    if check_password(increase_point_params)
      @increase_point = IncreasePoint.new(increase_point_params)

      respond_to do |format|
        if @increase_point.save
          format.html { redirect_to root_path, success: "Increase point was successfully created." }
          increase_user_points
          daywise_winners_list
        else
          format.html { render :new, danger: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /increase_points/1 or /increase_points/1.json
  # def update
  #   respond_to do |format|
  #     if @increase_point.update(increase_point_params)
  #       format.html { redirect_to @increase_point, notice: "Increase point was successfully updated." }
  #       format.json { render :show, status: :ok, location: @increase_point }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @increase_point.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /increase_points/1 or /increase_points/1.json
  # def destroy
  #   @increase_point.destroy
  #   respond_to do |format|
  #     format.html { redirect_to increase_points_url, notice: "Increase point was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_increase_point
      @increase_point = IncreasePoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def increase_point_params
      params.require(:increase_point).permit(:date, :winner1, :winner2, :password)
    end
end

app/helpers/increase_points_helper.rb
module IncreasePointsHelper
end

app/views/increase_points/_form.html.erb
<%= form_with(model: increase_point, local: true) do |form| %>
  <% if increase_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(increase_point.errors.count, "error") %> prohibited this increase_point from being saved:</h2>

      <ul>
        <% increase_point.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<center>
  <div class="field">
    <%= form.text_field :date, class: 'form-control', placeholder: "Enter Match date" %>
  </div>

  <div class="field">
    <%= form.text_field :winner1, class: 'form-control', placeholder: "Enter Match1 Winner"  %>
  </div>

  <div class="field">
    <%= form.text_field :winner2, class: 'form-control', placeholder: "Enter Match2 Winner" %>
  </div>

  <div class="field">
    <%= form.password_field :password, class: 'form-control', placeholder: "Enter Password" %>
  </div>
  
  <div class="actions">
    <%= form.submit 'Submit', class: 'save_button' %>
  </div>
  </center>
  
<% end %>

app/views/increase_points/edit.html.erb
<h1>Page not found</h1>
<% if false %>
<h1>Editing Increase Point</h1>

<%= render 'form', increase_point: @increase_point %>

<%= link_to 'Show', @increase_point %> |
<%= link_to 'Back', increase_points_path %>
<% end %>

app/views/increase_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Page not found</h1>
<% if false %>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Winner1</th>
      <th>Winner2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @increase_points.each do |increase_point| %>
      <tr>
        <td><%= increase_point.date %></td>
        <td><%= increase_point.winner1 %></td>
        <td><%= increase_point.winner2 %></td>
        <td><%= link_to 'Show', increase_point %></td>
        <td><%= link_to 'increase_user_points', new_increase_point_url %>
        <td><%= link_to 'Edit', edit_increase_point_path(increase_point) %></td>
        <td><%= link_to 'Destroy', increase_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Increase Point', new_increase_point_path %>
<% end %>

app/views/increase_points/new.html.erb
<h1 style="color:red;text-align:center;font-family:'Georgia';font-style: italic">Add the Match winners</h1>
<br><br><br>
<%= render 'form', increase_point: @increase_point %>

<%= link_to 'Back', increase_points_path %>

app/views/increase_points/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Page not found</h1>
<% if false%>
<p>
  <strong>Date:</strong>
  <%= @increase_point.date %>
</p>

<p>
  <strong>Winner1:</strong>
  <%= @increase_point.winner1 %>
</p>

<p>
  <strong>Winner2:</strong>
  <%= @increase_point.winner2 %>
</p>

<%= link_to 'Edit', edit_increase_point_path(@increase_point) %> |
<%= link_to 'Back', increase_points_path %> 
<% end %>

app/views/increase_points/view_winners.html.erb
<p id="notice"><%= notice %></p>
<h1 style="color:red;text-align:center;font-family:'Georgia';font-style: italic"><b>Daily Winners List</b></h1>
<br><br><br>
<center>
<b><%= link_to 'Home',root_path, class: 'button' %></b>
<b><%= link_to 'Scoreboard',users_path, class: 'button' %></b>
</center>
<br><br><br>
<table id='scoreboard'>
  <thead>
    <tr>
      <th rowspan="2">No</th>
      <th rowspan="2">Date</th>
      <th colspan="2">Match details</th>
      <th colspan="2">Winners</th>
    </tr>
    <tr>
      <th>Match1</th>
      <th>Match2</th>
      <th>Match1</th>
      <th>Match2</th>
    </tr>
  </thead>

  <tbody>
    <% WinnerTeamsUser.all.each_with_index do |winners, i| %>
      <tr>
        <td> <%= i+1 %> </td>
        <td><%= winners.date %></td>
        <td>
          <%= winners.match1 %> <br>
          <b>Winner:<span style='color:blue'> <%= winners.team1 %></span> </b>
        </td>
        <td>
          <% if winners.match2.present? %>
            <%= winners.match2 %> <br>
            <b>Winner:<span style='color:blue'> <%= winners.team2 %></span> </b>
          <% else %>
            No Match 
          <% end %>
        </td>
        <td> 
          <% if winners.winners1.present? %>
            <b> <%= winners.winners1 %></b> 
            <% else %>
              No Winners 
          <%end%>
        </td>
        <td>
          <% if winners.match2.present? %>
            <% if winners.winners2.present? %>
              <b> <%= winners.winners2 %></b> 
            <% else %>
              No Winners 
            <%end%>
          <% else %>
            No Match 
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>