config/routes.rb
Rails.application.routes.draw do
  resources :increase_points
  resources :match_predections
  # resources :users
  get '/users', to:'users#index'
  root 'match_predections#index'
  get '/winners', to: 'increase_points#view_winners'
  # get '/increase_points/new', to:'increase_points#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/match_predection.rb
class MatchPredection < ApplicationRecord
  before_save :set_date
  validates :name, presence: true
  def set_date
    today = Time.now.in_time_zone("Chennai").strftime("%-d-%b-%y")
    match_start_date = "9-Apr-21"
    self.date = Date.parse(today) >= Date.parse(match_start_date) ? today : match_start_date
  end 
end

app/controllers/match_predections_controller.rb
class MatchPredectionsController < ApplicationController
  before_action :set_match_predection, only: %i[ show edit update destroy ]
  # GET /match_predections or /match_predections.json
  def index
    @match_predections = MatchPredection.all
    @new_match_predection = MatchPredection.new
  end

  # GET /match_predections/1 or /match_predections/1.json
  def show
  end

  # GET /match_predections/new
  def new
    @match_predection = MatchPredection.new
  end

  # GET /match_predections/1/edit
  def edit
  end

  def create_users
    name = @match_predection.name.strip
    password = @match_predection.password.strip
    user_data = find_user(name)
    unless user_data
      user_data = {"name"=>name.capitalize, "point"=>0, "password"=>password}
      user = User.new(user_data)
      user.save!
      puts "New user created"
    end
  end

  def all_match_predection
    @all_match_predection = MatchPredection.all
  end

  def is_match_predection_present?(match_predection_params)
    all_match_predection
    @all_match_predection.find_by(name: match_predection_params['name'], date: MatchPredectionsHelper.get_date )
  end

  def find_user(name)
    @users = User.all
    @users.find_by_name(name)
  end

  # def get_date
  #   today = Time.now.strftime("%d-%b-%y")
  #   match_start_date = "9-Apr-21"
  #   today >= match_start_date ? today : match_start_date
  # end

  def name_capitalize(match_predection_params)
    match_predection_params['name'].capitalize!
  end

  def update_values(match_predection_params)
    all_match_predection
    get_date = MatchPredectionsHelper.get_date
    match_schedule = MatchPredectionsHelper::MATCH_SCHEDULE[get_date]
    @flash_error_message = ""
    match_schedule.each_with_index do |match, i|
      unless (match['start_time'] > Time.now.utc.strftime("%H:%M") || Time.parse(get_date) > Time.now)
        existing_data = is_match_predection_present?(match_predection_params)
        if existing_data
          current_value = existing_data["winners#{i+1}"]
          match_predection_params["winners#{i+1}"] = current_value
          puts "existing here #{match_predection_params}"
          @flash_error_message += "Predection Time closed for Match #{i+1}. Value can't be updated <br>"
        else
          match_predection_params["winners#{i+1}"] = nil
          puts "existing there #{match_predection_params}"
          @flash_error_message += "Predection Time closed for Match #{i+1}. <br>"
        end
        
      end
    end
    match_predection_params
  end

  # POST /match_predections or /match_predections.json
  def create
    user_detail = find_user(match_predection_params['name'])
    if (user_detail.nil? || (user_detail['password'] == match_predection_params['password']))
      name_capitalize(match_predection_params)
      update_match_predection_params = update_values(match_predection_params)
      @match_predections = MatchPredection.all
      existing_user_data = is_match_predection_present?(update_match_predection_params)

      if existing_user_data
          existing_user_data.winners1 = update_match_predection_params['winners1']
          existing_user_data.winners2 = update_match_predection_params['winners2']
          if !(update_match_predection_params['winners1'].nil? && update_match_predection_params['winners2'].nil?)
            existing_user_data.save!
            puts "Existing Match Predection data Updated \n #{existing_user_data}"
            respond_to do |format|
              unless @flash_error_message.empty?
                format.html { redirect_to root_path, danger: @flash_error_message.html_safe }
              else
                format.html { redirect_to root_path, success: "Match predection was successfully updated" }
              end
            end
          else 
            respond_to do |format|
              format.html { redirect_to root_path, danger: @flash_error_message.html_safe }
            end     
          end
      else
        update_match_predection_params['name'] = update_match_predection_params['name'].strip
        @match_predection = MatchPredection.new(update_match_predection_params)
        puts "New created Match Predection data created"
        if !(update_match_predection_params['winners1'].nil? && update_match_predection_params['winners2'].nil?)
          respond_to do |format|
            if @match_predection.save
              unless @flash_error_message.empty?
                format.html { redirect_to root_path, danger: @flash_error_message.html_safe }
              else
                format.html { redirect_to root_path, success: "Match predection was successfully created." }
              end
              puts "New created Match Predection data created data \n #{@match_predection}"
              create_users
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @match_predection.errors, status: :unprocessable_entity }
            end
          end
        else
          respond_to do |format|
              format.html { redirect_to root_path, danger: @flash_error_message.html_safe }
            end     
        end
        
      end
    else
      puts "Password incorrect"
      respond_to do |format|
        format.html { redirect_to root_path, danger: "Update failed Invalid password".html_safe }
      end
    end
    @flash_error_message = nil
  end


  # PATCH/PUT /match_predections/1 or /match_predections/1.json
  def update
    respond_to do |format|
      if @match_predection.update(match_predection_params)
        format.html { redirect_to @match_predection, notice: "Match predection was successfully updated." }
        format.json { render :show, status: :ok, location: @match_predection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match_predection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /match_predections/1 or /match_predections/1.json
  def destroy
    @match_predection.destroy
    respond_to do |format|
      format.html { redirect_to match_predections_url, notice: "Match predection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match_predection
      @match_predection = MatchPredection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_predection_params
      params.require(:match_predection).permit(:name, :date, :winners1, :winners2, :password)
    end
end

app/helpers/match_predections_helper.rb
module MatchPredectionsHelper
  MATCH_SCHEDULE = {
    '9-Apr-21'=>  [ {'team1' =>'Mumbai Indians', 'team2'=>'Royal Challengers Bangalore', 'start_time'=>'14:00'}],
    '10-Apr-21'=>  [ {'team1' =>'Chennai Super Kings', 'team2'=>'Delhi Capitals', 'start_time'=>'14:00'}],
    '11-Apr-21'=>  [ {'team1' =>'Sunrisers Hyderabad', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'14:00'}],
    '12-Apr-21'=>  [ {'team1' =>'Rajasthan Royals', 'team2'=>'Punjab Kings', 'start_time'=>'14:00'}],
    '13-Apr-21'=>  [ {'team1' =>'Kolkata Knight Riders', 'team2'=>'Mumbai Indians', 'start_time'=>'14:00'}],
    '14-Apr-21'=>  [ {'team1' =>'Sunrisers Hyderabad', 'team2'=>'Royal Challengers Bangalore', 'start_time'=>'14:00'}],
    '15-Apr-21'=>  [ {'team1' =>'Rajasthan Royals', 'team2'=>'Delhi Capitals', 'start_time'=>'14:00'}],
    '16-Apr-21'=>  [ {'team1' =>'Punjab Kings', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}],
    '17-Apr-21'=>  [ {'team1' =>'Mumbai Indians', 'team2'=>'Sunrisers Hyderabad', 'start_time'=>'14:00'}],
    '18-Apr-21'=>  [ {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'10:00'},
                    {'team1' =>'Delhi Capitals', 'team2'=>'Punjab Kings', 'start_time'=>'14:00'}],
    '19-Apr-21'=>  [ {'team1' =>'Chennai Super Kings', 'team2'=>'Rajasthan Royals', 'start_time'=>'14:00'}],
    '20-Apr-21'=>  [ {'team1' =>'Delhi Capitals', 'team2'=>'Mumbai Indians', 'start_time'=>'14:00'}],
    '21-Apr-21'=>  [ {'team1' =>'Punjab Kings', 'team2'=>'Sunrisers Hyderabad', 'start_time'=>'10:00'},
                    {'team1' =>'Kolkata Knight Riders', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}],
    '22-Apr-21'=>  [ {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Rajasthan Royals', 'start_time'=>'14:00'}],
    '23-Apr-21'=>  [ {'team1' =>'Punjab Kings', 'team2'=>'Mumbai Indians', 'start_time'=>'14:00'}],
    '24-Apr-21'=>  [ {'team1' =>'Rajasthan Royals', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'14:00'}],
    '25-Apr-21'=>  [ {'team1' =>'Chennai Super Kings', 'team2'=>'Royal Challengers Bangalore', 'start_time'=>'10:00'},
                    {'team1' =>'Sunrisers Hyderabad', 'team2'=>'Delhi Capitals', 'start_time'=>'14:00'}],
    '26-Apr-21'=>  [ {'team1' =>'Punjab Kings', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'14:00'}],
    '27-Apr-21'=>  [ {'team1' =>'Delhi Capitals', 'team2'=>'Royal Challengers Bangalore', 'start_time'=>'14:00'}],
    '28-Apr-21'=>  [ {'team1' =>'Chennai Super Kings', 'team2'=>'Sunrisers Hyderabad', 'start_time'=>'14:00'}],
    '29-Apr-21'=>  [ {'team1' =>'Mumbai Indians', 'team2'=>'Rajasthan Royals', 'start_time'=>'10:00'},
                    {'team1' =>'Delhi Capitals', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'14:00'}],
    '30-Apr-21'=>  [ {'team1' =>'Punjab Kings', 'team2'=>'Royal Challengers Bangalore', 'start_time'=>'14:00'}],
    '1-May-21'=>  [ {'team1' =>'Mumbai Indians', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}],
    '2-May-21'=>  [ {'team1' =>'Rajasthan Royals', 'team2'=>'Sunrisers Hyderabad', 'start_time'=>'10:00'},
                    {'team1' =>'Punjab Kings', 'team2'=>'Delhi Capitals', 'start_time'=>'14:00'}],
    '19-Sep-21'=>  [ {'team1' =>'Chennai Super Kings', 'team2'=>'Mumbai Indians', 'start_time'=>'14:00'}],
    '20-Sep-21'=>  [ {'team1' =>'Kolkata Knight Riders', 'team2'=>'Royal Challengers Bangalore', 'start_time'=>'14:00'}],
    '21-Sep-21'=>  [ {'team1' =>'Punjab Kings', 'team2'=>'Rajasthan Royals', 'start_time'=>'14:00'}],
    '22-Sep-21'=>  [ {'team1' =>'Delhi Capitals', 'team2'=>'Sunrisers Hyderabad', 'start_time'=>'14:00'}],
    '23-Sep-21'=>  [ {'team1' =>'Mumbai Indians', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'14:00'}],
    '24-Sep-21'=>  [ {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}],
    '25-Sep-21'=>  [ {'team1' =>'Delhi Capitals', 'team2'=>'Rajasthan Royals', 'start_time'=>'10:00'},
                      {'team1' =>'Sunrisers Hyderabad', 'team2'=>'Punjab Kings', 'start_time'=>'14:00'}],
    '26-Sep-21'=>  [ {'team1' =>'Chennai Super Kings', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'10:00'},
                      {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Mumbai Indians', 'start_time'=>'14:00'}],
    '27-Sep-21'=>  [ {'team1' =>'Sunrisers Hyderabad', 'team2'=>'Rajasthan Royals', 'start_time'=>'14:00'}],
    '28-Sep-21'=>  [ {'team1' =>'Kolkata Knight Riders', 'team2'=>'Delhi Capitals', 'start_time'=>'10:00'},
                      {'team1' =>'Mumbai Indians', 'team2'=>'Punjab Kings', 'start_time'=>'14:00'}],
    '29-Sep-21'=>  [ {'team1' =>'Rajasthan Royals', 'team2'=>'Royal Challengers Bangalore', 'start_time'=>'14:00'}],
    '30-Sep-21'=>  [ {'team1' =>'Sunrisers Hyderabad', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}],
    '1-Oct-21'=>    [ {'team1' =>'Kolkata Knight Riders', 'team2'=>'Punjab Kings', 'start_time'=>'14:00'}],
    '2-Oct-21'=>    [ {'team1' =>'Mumbai Indians', 'team2'=>'Delhi Capitals', 'start_time'=>'10:00'},
                      {'team1' =>'Rajasthan Royals', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}],
    '3-Oct-21'=>    [ {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Punjab Kings', 'start_time'=>'10:00'},
                      {'team1' =>'Kolkata Knight Riders', 'team2'=>'Sunrisers Hyderabad', 'start_time'=>'14:00'}],
    '4-Oct-21'=>  [ {'team1' =>'Delhi Capitals', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}],
    '5-Oct-21'=>  [ {'team1' =>'Rajasthan Royals', 'team2'=>'Mumbai Indians', 'start_time'=>'14:00'}],
    '6-Oct-21'=>  [ {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Sunrisers Hyderabad', 'start_time'=>'14:00'}],
    '7-Oct-21'=>    [ {'team1' =>'Chennai Super Kings', 'team2'=>'Punjab Kings', 'start_time'=>'10:00'},
                      {'team1' =>'Kolkata Knight Riders', 'team2'=>'Rajasthan Royals', 'start_time'=>'14:00'}],
    '8-Oct-21'=>    [ {'team1' =>'Sunrisers Hyderabad', 'team2'=>'Mumbai Indians', 'start_time'=>'10:00'},
                      {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Delhi Capitals', 'start_time'=>'14:00'}],
    '10-Oct-21'=>  [ {'team1' =>'Chennai Super Kings', 'team2'=>'Delhi Capitals', 'start_time'=>'14:00'}],
    '11-Oct-21'=>  [ {'team1' =>'Royal Challengers Bangalore', 'team2'=>'Kolkata Knight Riders', 'start_time'=>'14:00'}],
    '13-Oct-21'=>  [ {'team1' =>'Kolkata Knight Riders', 'team2'=>'Delhi Capitals', 'start_time'=>'14:00'}],
    # '15-May-21'=>  [ {'team1' =>'', 'team2'=>'Chennai Super Kings', 'start_time'=>'14:00'}]
  }

  TEAM_COLOR = {
    'Mumbai Indians' => '#004ba0',
    'Chennai Super Kings' => '#fcce06',
    'Kolkata Knight Riders' => '#3a225d',
    'Punjab Kings'=> '#f04a4a',
    'Rajasthan Royals'=>'#e73895',
    'Delhi Capitals'=>'#00008b',
    'Sunrisers Hyderabad'=>'#FF822A',
    'Royal Challengers Bangalore' => '#d5152c'
   }

   def self.get_date
      today = Time.now.in_time_zone("Chennai").strftime("%-d-%b-%y")
      match_start_date = "9-Apr-21"
      Date.parse(today) >= Date.parse(match_start_date) ? today : match_start_date
   end
end

app/views/match_predections/_form.html.erb
<%= form_with(model: match_predection, local: true) do |form| %>
  <% if match_predection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match_predection.errors.count, "error") %> prohibited this match_predection from being saved:</h2>

      <ul>
        <% match_predection.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :winners %>
    <%= form.text_field :winners %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/match_predections/edit.html.erb
<% if false %>
<h1>Editing Match Predection</h1>

<%= render 'form', match_predection: @match_predection %>

<%= link_to 'Show', @match_predection %> |
<%= link_to 'Back', match_predections_path %>

<% end %>

app/views/match_predections/index.html.erb
<h1 style="color:red;text-align:center;font-family:'Georgia';font-style: italic">
  <b>Predict The Winning Team </b>
</h1>
<p class="text_center"> Click on the card to select the team</p>
<br><br><br>
<center>
  <b><%= link_to 'Scoreboard',users_path, class: 'button' %></b>
  <b><%= link_to 'Daily Winners list',winners_path, class: 'button' %></b>
</center>
<% match_number = 1%>
<% today = Time.now.in_time_zone("Chennai").strftime("%-d-%b-%y") %>
<% match_start_date = "9-Apr-21" %>
<br><br><br>
<% today_match = Date.parse(today) >= Date.parse(match_start_date) ? today : match_start_date %>
<% all_match = MatchPredectionsHelper::MATCH_SCHEDULE[today_match] %>
<% unless all_match.nil? %>
  <% match = all_match.first %>
  <% team_color = MatchPredectionsHelper::TEAM_COLOR %>
  <script>
    function myFunction() {
    var x = document.getElementById("match_predection_password");
    if (x.type === "password") {
      x.type = "text";
    } else {
      x.type = "password";
    }
  }
  </script>
  <%= form_for @new_match_predection do |f| %>
    <center>
      <%= f.text_field :name, class: 'form-control captitalize', placeholder: "Enter Your Name", required: true %> 
      <%= f.password_field :password, class: 'form-control', placeholder: "Enter Your Password", required: true %>
      <input class="form-check-input" type="checkbox" onclick="myFunction()">Show Password
      <br><br><br>
      <h1 style="text-align:center"> <%= today_match %> Matches </h1>
      <br><br><br>
      <h1> Match <%= match_number %> </h1>
      <% end_time = all_match.count > 1 ? "3:30 PM" : "7:30 PM" %>
      <h6> You can select the team till <%= end_time %> </h6>
      <br><br><br>
      
      <div class="row">
        <%= f.collection_radio_buttons(:winners1, [[match['team1'], match['team1']] ,[match['team2'], match['team2']] ], :first, :last) do |b| %>
          <div class="column">
            <div class="card">
              <%= b.label { b.radio_button(class: "checkmark",checked: true,required: true) + image_tag(b.text+'.jpg', style: "width:300px;border-radius: 15px 15px 15px 15px;") } %>
              <div class="container">
                <h6><%= b.text %></h6>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div>
        <% match_predection_data = MatchPredection.where(date: today_match) %>
        <% winners1_data = match_predection_data.group(:winners1).count %>
        <% winners1_data.delete_if{|k,v| k.class == nil.class } %>
        <% total = winners1_data.values.sum %>
        <% winner_percentage = winners1_data.transform_values { |v| (v * 100.0 / total).round(0) } %>
        <% user_names = match_predection_data.collect(&:name) %>
        <% unless winner_percentage.empty? %>
          <p class="text-muted"> <b> Participants: </b> <%= user_names.join(',') %> </p>
          <div class="progress" style="height: 25px;width: 70%;border-radius: 55px">
            
            <% if winner_percentage.values.second %>
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width:<%= winner_percentage[match['team1']] %>%;background-color: <%= team_color[match['team1']]%>" aria-valuenow="<%= winner_percentage[match['team1']] %>" aria-valuemin="0" aria-valuemax="100">
                <b>
                  <%= match['team1'].split.map(&:first).join %>  
                  <%= winner_percentage[match['team1']] %>%
                </b>
              </div>
              <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: <%= winner_percentage[match['team2']] %>%;background-color: <%= team_color[match['team2']]%>" role="progressbar" aria-valuenow="<%= winner_percentage[match['team2']] %>" aria-valuemin="0" aria-valuemax="100">
                <b>
                  <%= match['team2'].split.map(&:first).join %> 
                  <%= winner_percentage[match['team2']] %>%
                </b>
              </div>
            <% else %>
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width:<%= winner_percentage.values.first %>%;background-color: <%= team_color[winner_percentage.keys.first]%>" aria-valuenow="<%= winner_percentage.values.first %>" aria-valuemin="0" aria-valuemax="100">
                <b>
                  <%= winner_percentage.keys.first.split.map(&:first).join %>  
                  <%= winner_percentage.values.first %>%
                </b>
              </div>
            <% end %>

          </div>
          
        <% end %>

      </div>
      
      <br><br><br><br>
      <% match_number+= 1%>

      <% if all_match.count > 1 %>
        <% match = all_match.last %>
        <h1> Match <%= match_number %> </h1>
        <h6> You can select the team till 7:30 PM </h6>
        <br><br><br>
        
        <div class="row">
          <%= f.collection_radio_buttons(:winners2, [[match['team1'], match['team1']] ,[match['team2'], match['team2']] ], :first, :last,html_options: { class: 'form-control' }) do |b| %>
            <div class="column">
              <div class="card">
                <%= b.label { b.radio_button(class: "checkmark",checked: true,required: true) + image_tag(b.text+'.jpg', style: "width:300px;border-radius: 15px 15px 15px 15px;") } %>
                <div class="container">
                  <h6><%= b.text %></h6>
                </div>
              </div>
            </div>
          <% end %>
        </div>

        <div>
          <% match_predection_data = MatchPredection.where(date: today_match) %>
          <% winners2_data = match_predection_data.group(:winners2).count %>
          <% total = winners2_data.values.sum %>
          <% winner_percentage = winners2_data.transform_values { |v| (v * 100.0 / total).round(0) } %>
          <% user_names = match_predection_data.collect(&:name) %>
          <% unless winner_percentage.empty? %>
            <p class="text-muted"> <b> Participants: </b> <%= user_names.join(',') %> </p>
            <div class="progress" style="height: 25px;width: 70%;border-radius: 55px">
              
              <% if winner_percentage.values.second %>
                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width:<%= winner_percentage[match['team1']] %>%;background-color: <%= team_color[match['team1']]%>" aria-valuenow="<%= winner_percentage[match['team1']] %>" aria-valuemin="0" aria-valuemax="100">
                  <b>
                    <%= match['team1'].split.map(&:first).join %>  
                    <%= winner_percentage[match['team1']] %>%
                  </b>
                </div>
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: <%= winner_percentage[match['team2']] %>%;background-color: <%= team_color[match['team2']]%>" role="progressbar" aria-valuenow="<%= winner_percentage[match['team2']] %>" aria-valuemin="0" aria-valuemax="100">
                  <b>
                    <%= match['team2'].split.map(&:first).join %> 
                    <%= winner_percentage[match['team2']] %>%
                  </b>
                </div>
              <% else %>
                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width:<%= winner_percentage.values.first %>%;background-color: <%= team_color[winner_percentage.keys.first]%>" aria-valuenow="<%= winner_percentage.values.first %>" aria-valuemin="0" aria-valuemax="100">
                  <b>
                    <%= winner_percentage.keys.first.split.map(&:first).join %>  
                    <%= winner_percentage.values.first %>%
                  </b>
                </div>
              <% end %>

            </div>
            
          <% end %>

        </div>
        
        <br><br>
      <% end %>
    
      <%= f.submit "Submit", class: 'save_button' %>
    </center>
    
  <% end %>
<% else %>
  <center>
    <h1> NO Match Today</h1>
  </center>
<%end%>

app/views/match_predections/new.html.erb
<% if false %>
<h1>New Match Predection</h1>

<%= render 'form', match_predection: @match_predection %>

<%= link_to 'Back', match_predections_path %>
<% end %>

app/views/match_predections/show.html.erb
<p id="notice"><%= notice %></p>
<% if false %>
<p>
  <strong>Name:</strong>
  <%= @match_predection.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @match_predection.date %>
</p>

<p>
  <strong>Winners:</strong>
  <%= @match_predection.winners1 %>
  <%= @match_predection.winners2 %>
</p>

<%= link_to 'Edit', edit_match_predection_path(@match_predection) %> |
<%= link_to 'Back', match_predections_path %>
<%end%>